server:
  port: 8081

spring:
  datasource:
    phoenix:
      username:
      password:
      url: jdbc:phoenix:127.0.0.1:2181
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
    druid:
      username:
      password:
      url: jdbc:phoenix:127.0.0.1:2181
      driver-class-name: org.apache.phoenix.jdbc.PhoenixDriver
      type: com.alibaba.druid.pool.DruidDataSource

  #druid 数据源专有配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: false
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
  #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
  #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
  #则导入 log4j 依赖即可，Maven 地址： https://mvnrepository.com/artifact/log4j/log4j
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: com.example.demo.phoenix.entity
    configuration:
      map-underscore-to-camel-case : true
 # resources:
 #   chain:
 #     cache: false
 #   static-locations: file:///home/hadoopuser/IdeaProjects/demo/src/main/resources/static/,file:///home/hadoopuser/IdeaProjects/demo/src/main/resources/,file:///home/hadoopuser/IdeaProjects/demo/src/main/resources/templates/
 # mvc:
 #   static-path-pattern: /static/**
#showSql
logging:
  level:
    com:
      example:
        demo : info
